import './globals.css'
import type { Metadata } from 'next'
import { Roboto_Flex as Roboto } from 'next/font/google'
import { Header } from './components/Header'
import { TransactionsProvider } from './contexts/TransactionContext'

const roboto = Roboto({
  subsets: ['latin'],
  variable: '--font-roboto',
})

export const metadata: Metadata = {
  title: 'DT Money',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      className={`${roboto.variable} font-sans leading-160 antialiased`}
    >
      <TransactionsProvider>
        <body>
          <div className="flex min-h-screen flex-col">
            <Header />
            <main className="flex-1 bg-gray-2 px-6 lg:px-40">{children}</main>
          </div>
        </body>
      </TransactionsProvider>
    </html>
  )
}
